### ISSUE TITLE
Upgrade components (bimonthly) - July 2022

### ISSUE THREAD

**Issue by etavela** [greenlight-coop/infrastructure#194]
# Tasks
- [x] Upgrade specific tasks
  - [x] Troubleshoot worker-ui 
  - [x] Revise cert-manager and certificate generation as separate boolean parameters 
  - [x] Edit issue checklist to adapt to new shared Node package structure
  - [x] Make size of k8ssandra cluster adjustable for dev and prod deployments
    - [x] replication_factor also needs separate setting depending on number of nodes available
    - [x] Edit k8ssandra-cluster.yaml, cassandra-setup.cql among others
    - [x] Test with Digital Ocean
  - [x] Make number of keycloak servers configurable
  - [x] Revise root .nvmrc and remove from projects 
  - [x] Change build targets from build-clean to build:clean
  - [x] Look into npm WARN config only Use `--omit=dev` to omit dev dependencies from the install
  - [x] Make npm audit configuration consistent with helloworld-ui in projects
  - [x] Update to serenity-js 3.0.0-rc
  - [x] Lock down to a specific chrome version in serenity-js-runner Dockerfile
  - [x] Split greenlight-serenity-js - greenlight-serenity-js-rest and greenlight-serenity-js-web
    - [x] Revise api-tests, helloworld and worker to use greenlight-serenity-js-rest
    - [x] Revise ui-tests to use greenlight-serenity-js-web
- [x] Upgrade development tools
  - [x] brew upgrade octant helm kn kubernetes-cli k9s argocd tektoncd-cli
  - [x] Docker Desktop 
- [x] Upgrade Terraform
  - [x] Terraform CLI
  - [x] Terraform Providers 
- [x] Upgrade Argo CD
- [x] Upgrade Kubernetes cluster version for DigitalOcean
- [x] Upgrade kind
  - [x] brew upgrade kind 
  - [x] Upgrade metrics-server
- [x] Upgrade all components in Argo CD Infrastructure project
  - [x] Monitoring: Loki, Promtail, kube-prometheus-stack
  - [x] Tekton Pipelines
  - [x] Tekton Triggers
  - [x] Tekton Dashboard
  - [x] Tekton Catalog tasks
  - [x] buildkit
    - [x] Server
    - [x] Image version in Tasks 
  - [x] verdaccio
  - [x] gcr.io/cloud-builders/kubectl image (find references in Tasks)
  - [x] Istio
    - [x] Kiali Operator 
  - [x] Knative
    - [x] Serving
    - [x] Eventing 
  - [x] Kafka
  - [x] Keycloak
  - [x] external-dns 
  - [x] cert-manager
  - [x] k8ssandra
    - [x] operator version in 00-k8ssandra-operator.yaml
    - [x] server version in k8ssandra-cluster.yaml
  - [x] Rook
- [x] Update root .nvmrc
- [x] Upgrade software projects in order (update package.json dependencies in all)
  - [x] prettier-config-greenlight
  - [x] eslint-config-greenlight
  - [x] eslint-config-greenlight-react
  - [x] greenlight-dev
  - [x] greenlight-utils
  - [x] greenlight-serenity-js
  - [x] serenity-js-runner
    - [x] Dockerfile (including chrome version to match chromedriver in greenlight-serenity-js)
    - [x] Update image in run-serenity-tests-task.yaml (2 occurrences)
  - [x] expose-pipeline-workspace
    - [x] Update nginx version in deployment 
    - [x] Update version in run-serenity-tests-tasks.yaml
  - [x] helloworld
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
    - [x] Test Tekton build to check greenlight-serenity-js, expose-pipeline-workspace, serenity-js-runner upgrades
  - [x] cooperatives
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
  - [x] greenlight-react
  - [x] helloworld-ui
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
  - [x] worker-ui
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
    - [x] Update greenlight-application with latest versions and build updated greenlight-test to check React changes 
  - [x] greenlight-api-tests
    - [x] Dockerfile 
  - [x] greenlight-ui-tests
    - [x] Dockerfile
    - [x] Update greenlight-test to check test changes
  - [x] node-utils
    - [x] Dockerfile
    - [x] Search for node-utils in ./argocd-greenlight-infrastructure/development and update image versions
  - [x] snyk-tools
    - [x] Dockerfile
    - [x] Search for snyk-tools in ./argocd-greenlight-infrastructure/development and update image versions
  - [x] template-processor
    - [x] Dockerfile
    - [x] Update image versions in parse-templates-task.yaml
  - [x] cassandra-liquibase 
    - [x] Dockerfile
  - [x] If necessary, for updates to node-noop, etc.
    - [x]  greenlight-application-resources
    - [x]  greenlight-application
    - [x]  greenlight-application-test-resources
- [x] Test to ensure all components are working:
  - [x] Build cooperatives component
    - [x] Ensure image pushed
    - [x] Ensure test results are accessible
    - [x] Ensure resources (preview images, staged preview) are cleaned up on close
  - [x] Deploy test stage
    - [x] Ensure all tests pass
    - [x] Check that test results are accessible
  - [x] Deploy staging stage
  - [ ] Check build and deployment in both kind and DigitalOcean
- [x] Make a copy of this ticket for two months out
  - [x] Link new copy to this current issue to refer to comments, etc. 
# Notes: 

### Tekton 
May want to remove `app.kubernetes.io/instance: default` from CRDs in the following to prevent SharedResourceWarning
- tekton-dashboard-release.yaml
- tekton-pipelines-release.yaml
- tekton-triggers-release.yaml

### Istio

Download with:
    curl -L https://istio.io/downloadIstio | ISTIO_VERSION=<x.y.x> TARGET_ARCH=x86_64 sh -

### Knative
May need to make some manual edits to resources due to duplicate resources
- knative-eventing-kafka-controller.yaml
  - Remove config-tracing ConfigMap
  - Remove CRD kafkachannels.messaging.knative.dev

### Rook
Ensure various edits in `cluster-on-pvc.yaml` are applied if replacing this file.

### kube-prometheus-stack
Updated kube-prometheus-stack charts need to be pulled and the annotation `argocd.argoproj.io/sync-options: Replace=true` added to the CRD prometheuses.monitoring.coreos.com.

### Node

When upgrading Node version, may need to revise tsconfig to reference new major version base tsconfig.json

Previous upgrade issues: #184
