### ISSUE TITLE
Upgrade components (bimonthly) - October 2022

### ISSUE THREAD

**Issue by etavela** [greenlight-coop/infrastructure#216]
# Tasks
- [x] Upgrade specific tasks
  - [x] Increase max-pods on link 
  - [x] Attempt to fix v0.22.0 (or latest) tekton-triggers upgrade (fails currently with "message": "Post \"\": unsupported protocol scheme \"\"") 
  - [x] Attempt to fix v0.42.0 (or latest) tekton-pipelines upgrade (apparent pod security issue) 
  - [x] Roll back current Axios changes to fix errors in helloworld-ui
    - [x] First try upgrading to latest jest 
  - [x] Convert package.jsons to use "exports" field rather than "main"
  - [x] Add snyk:test to projects
  - [x] Add /node_modules to .helmignore - shouldn't be packaged with charts
  - [x] Rename `*.spec.ts` to `*.test.ts` and update Jest, tsconfig etc. accordingly (consider leaving React projects as-is)
  - [x] Add "type": "module" to modules
    - [x] Research different modules (es and CommonJS) first and potentially defer this to a new task on the backlog 
  - [x] Replace `npm audit --production...` with `npm audit --omit=dev...` in all package.json usages
  - [x] Upgrade to k8ssandra-operator v1.3.1 (or latest)
  - [x] See if build performance can be improved by revising limits
  - [x] Upgrade link to latest kubeadm, etc. (note - compatibility issues with existing components, do component upgrades first and evaluate issues)
  - [x] Fix kind (version 1.25 compatibility issues)
- [x] Upgrade development tools
  - [x] brew upgrade argocd buildkit git helm httpie hub jq k9s kind kn kubernetes-cli octant tektoncd-cli tmux wget yq
  - [x] Docker Desktop 
- [x] Upgrade Terraform
  - [x] brew upgrade terraform
  - [x] Terraform Providers 
- [x] Upgrade Argo CD
- [x] Upgrade Kubernetes cluster version for DigitalOcean
- [x] Upgrade kind
  - [x] brew upgrade kind 
- [x] Upgrade all components in Argo CD Infrastructure project
  - [x] Gatekeeper
  - [x] Upgrade metrics-server
  - [x] Monitoring: Loki, Promtail, kube-prometheus-stack
  - [x] Tekton Pipelines
  - [x] Tekton Triggers
  - [x] Tekton Dashboard
  - [x] Tekton Catalog tasks
  - [x] buildkit
    - [x] Server
    - [x] Image version in Tasks 
  - [x] verdaccio
  - [x] gcr.io/cloud-builders/kubectl image (find references in Tasks)
  - [x] Istio
    - [x] Kiali Operator 
  - [x] Knative
    - [x] Serving
    - [x] Eventing 
  - [x] Kafka
  - [x] Keycloak
  - [x] external-dns 
  - [x] cert-manager
  - [x] k8ssandra
    - [x] operator version in 00-k8ssandra-operator.yaml
    - [x] server version in k8ssandra-cluster.yaml
  - [x] Rook
- [x] Update root .nvmrc
- [x] Upgrade software projects in order (update package.json dependencies in all)
  - [x] prettier-config-greenlight
  - [x] eslint-config-greenlight
  - [x] eslint-config-greenlight-react
  - [x] greenlight-dev
  - [x] greenlight-utils
  - [x] greenlight-build-utils
  - [x] node-utils
    - [x] Dockerfile
    - [x] Search for node-utils in ./argocd-greenlight-infrastructure/development and update image versions
  - [x] snyk-tools
    - [x] Dockerfile
    - [x] Search for snyk-tools in ./argocd-greenlight-infrastructure/development and update image versions
  - [x] template-processor
    - [x] Dockerfile
    - [x] Update image versions in parse-templates-task.yaml
  - [x] cassandra-liquibase 
    - [x] Dockerfile
  - [x] greenlight-serenity-js
  - [x] greenlight-serenity-js-rest
  - [x] greenlight-serenity-js-web
  - [x] serenity-js-runner
    - [x] Dockerfile (including chrome version to match chromedriver in greenlight-serenity-js-web)
    - [x] Update image in run-serenity-tests-task.yaml
  - [x] expose-pipeline-workspace
    - [x] Update nginx version in deployment 
    - [x] Update version in run-serenity-tests-tasks.yaml
  - [x] helloworld-service
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
    - [x] Test Tekton build to check greenlight-serenity-js, expose-pipeline-workspace, serenity-js-runner upgrades
  - [x] cooperatives-service
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
  - [x] greenlight-react
  - [x] admin-ui
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
  - [x] helloworld-ui
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
  - [x] worker-ui
    - [x] Dockerfile 
    - [x] greenlight-helm-library version
    - [x] Update greenlight-application with latest versions and build updated greenlight-test to check React changes 
  - [x] greenlight-api-tests
    - [x] Dockerfile 
  - [x] greenlight-ui-tests
    - [x] Dockerfile
    - [x] Update greenlight-test to check test changes
  - [x] If necessary, for updates to node-noop, etc.
    - [x]  greenlight-application-resources
    - [x]  greenlight-application
    - [x]  greenlight-application-test-resources
- [x] Test to ensure all components are working:
  - [x] Test that Keycloak integrated UIs can be run locally via npm start (e.g. worker-ui) 
  - [x] Build cooperatives component
    - [x] Ensure image pushed
    - [x] Ensure test results are accessible
    - [x] Ensure resources (preview images, staged preview) are cleaned up on close
  - [x] Deploy test stage
    - [x] Ensure all tests pass
    - [x] Check that test results are accessible
  - [x] Deploy staging stage
  - [x] Check build and deployment in both kind and link
- [x] Make a copy of this ticket for two months out
  - [x] Link new copy to this current issue to refer to comments, etc. 
# Notes: 

### Tekton 
May want to remove `app.kubernetes.io/instance: default` from CRDs in the following to prevent SharedResourceWarning
- tekton-dashboard-release.yaml
- tekton-pipelines-release.yaml
- tekton-triggers-release.yaml

### Istio

Download with:
    curl -L https://istio.io/downloadIstio | ISTIO_VERSION=<x.y.x> TARGET_ARCH=x86_64 sh -

### Knative
May need to make some manual edits to resources due to duplicate resources
- knative-eventing-kafka-controller.yaml
  - Remove config-tracing ConfigMap
  - Remove CRD kafkachannels.messaging.knative.dev

### Rook
Ensure various edits in `cluster-on-pvc.yaml` are applied if replacing this file.

### kube-prometheus-stack
Updated kube-prometheus-stack charts need to be pulled and the annotation `argocd.argoproj.io/sync-options: Replace=true` added to the CRD prometheuses.monitoring.coreos.com.

### Node

When upgrading Node version, may need to revise tsconfig to reference new major version base tsconfig.json

Previous upgrade issues: #194

**Comment by etavela** [comment]
Skipped upgraded Tekton catalog components

**Comment by etavela** [comment]
Skipped Kiali and Kafka upgrades

**Comment by etavela** [comment]
Skipped Keycloak upgrade

**Comment by etavela** [comment]
Skipped external-dns upgrade

**Comment by etavela** [comment]
Skipped Rook upgrade
