### ISSUE TITLE
Upgrade components (bimonthly) - Feburary 2023

### ISSUE THREAD

**Issue by etavela** [greenlight-coop/infrastructure#240]
# Tasks
- [ ] Upgrade specific tasks
  - [ ] Attempt to fix v0.22.0 (or latest) tekton-triggers upgrade (fails currently with "message": "Post \"\": unsupported protocol scheme \"\"") 
  - [ ] Attempt to fix v0.42.0 (or latest) tekton-pipelines upgrade (apparent pod security issue) 
  - [ ] Upgrade link to latest kubeadm, etc. (note - compatibility issues with existing components, do component upgrades first and evaluate issues)
  - [ ] Fix kind (version 1.25 compatibility issues)
- [ ] Upgrade development tools
  - [ ] brew upgrade argocd buildkit git helm httpie hub jq k9s kind kn kubernetes-cli octant tektoncd-cli tmux wget yq
  - [ ] Docker Desktop 
- [ ] Upgrade Terraform
  - [ ] brew upgrade terraform
  - [ ] Terraform Providers 
- [ ] Upgrade Argo CD
- [ ] Upgrade Kubernetes cluster version for DigitalOcean
- [ ] Upgrade kind
  - [ ] brew upgrade kind 
- [ ] Upgrade all components in Argo CD Infrastructure project
  - [ ] Gatekeeper
  - [ ] Upgrade metrics-server
  - [ ] Monitoring: Loki, Promtail, kube-prometheus-stack
  - [ ] Tekton Pipelines
  - [ ] Tekton Triggers
  - [ ] Tekton Dashboard
  - [ ] Tekton Catalog tasks
  - [ ] buildkit
    - [ ] Server
    - [ ] Image version in Tasks 
  - [ ] verdaccio
  - [ ] gcr.io/cloud-builders/kubectl image (find references in Tasks)
  - [ ] Istio
    - [ ] Kiali Operator 
  - [ ] Knative
    - [ ] Serving
    - [ ] Eventing 
  - [ ] Kafka
  - [ ] Keycloak
  - [ ] external-dns 
  - [ ] cert-manager
  - [ ] k8ssandra
    - [ ] operator version in 00-k8ssandra-operator.yaml
    - [ ] server version in k8ssandra-cluster.yaml
  - [ ] Rook
- [ ] Update root .nvmrc
- [ ] Upgrade software projects in order (update package.json dependencies in all)
  - [ ] prettier-config-greenlight
  - [ ] eslint-config-greenlight
  - [ ] eslint-config-greenlight-react
  - [ ] greenlight-dev
  - [ ] greenlight-utils
  - [ ] greenlight-build-utils
  - [ ] node-utils
    - [ ] Dockerfile
    - [ ] Search for node-utils in ./argocd-greenlight-infrastructure/development and update image versions
  - [ ] snyk-tools
    - [ ] Dockerfile
    - [ ] Search for snyk-tools in ./argocd-greenlight-infrastructure/development and update image versions
  - [ ] template-processor
    - [ ] Dockerfile
    - [ ] Update image versions in parse-templates-task.yaml
  - [ ] cassandra-liquibase 
    - [ ] Dockerfile
  - [ ] greenlight-serenity-js
  - [ ] greenlight-serenity-js-rest
  - [ ] greenlight-serenity-js-web
  - [ ] serenity-js-runner
    - [ ] Dockerfile (including chrome version to match chromedriver in greenlight-serenity-js-web)
    - [ ] Update image in run-serenity-tests-task.yaml
  - [ ] expose-pipeline-workspace
    - [ ] Update nginx version in deployment 
    - [ ] Update version in run-serenity-tests-tasks.yaml
  - [ ] helloworld-service
    - [ ] Dockerfile 
    - [ ] greenlight-helm-library version
    - [ ] Test Tekton build to check greenlight-serenity-js, expose-pipeline-workspace, serenity-js-runner upgrades
  - [ ] cooperatives-service
    - [ ] Dockerfile 
    - [ ] greenlight-helm-library version
  - [ ] greenlight-react
  - [ ] admin-ui
    - [ ] Dockerfile 
    - [ ] greenlight-helm-library version
  - [ ] helloworld-ui
    - [ ] Dockerfile 
    - [ ] greenlight-helm-library version
  - [ ] worker-ui
    - [ ] Dockerfile 
    - [ ] greenlight-helm-library version
    - [ ] Update greenlight-application with latest versions and build updated greenlight-test to check React changes 
  - [ ] greenlight-api-tests
    - [ ] Dockerfile 
  - [ ] greenlight-ui-tests
    - [ ] Dockerfile
    - [ ] Update greenlight-test to check test changes
  - [ ] If necessary, for updates to node-noop, etc.
    - [ ]  greenlight-application-resources
    - [ ]  greenlight-application
    - [ ]  greenlight-application-test-resources
- [ ] Test to ensure all components are working:
  - [ ] Test that Keycloak integrated UIs can be run locally via npm start (e.g. worker-ui) 
  - [ ] Build cooperatives component
    - [ ] Ensure image pushed
    - [ ] Ensure test results are accessible
    - [ ] Ensure resources (preview images, staged preview) are cleaned up on close
  - [ ] Deploy test stage
    - [ ] Ensure all tests pass
    - [ ] Check that test results are accessible
  - [ ] Deploy staging stage
  - [ ] Check build and deployment in both kind and link
- [ ] Make a copy of this ticket for two months out
  - [ ] Link new copy to this current issue to refer to comments, etc. 
# Notes: 

### Tekton 
May want to remove `app.kubernetes.io/instance: default` from CRDs in the following to prevent SharedResourceWarning
- tekton-dashboard-release.yaml
- tekton-pipelines-release.yaml
- tekton-triggers-release.yaml

### Istio

Download with:
    curl -L https://istio.io/downloadIstio | ISTIO_VERSION=<x.y.x> TARGET_ARCH=x86_64 sh -

### Knative
May need to make some manual edits to resources due to duplicate resources
- knative-eventing-kafka-controller.yaml
  - Remove config-tracing ConfigMap
  - Remove CRD kafkachannels.messaging.knative.dev

### Rook
Ensure various edits in `cluster-on-pvc.yaml` are applied if replacing this file.

### kube-prometheus-stack
Updated kube-prometheus-stack charts need to be pulled and the annotation `argocd.argoproj.io/sync-options: Replace=true` added to the CRD prometheuses.monitoring.coreos.com.

### Node

When upgrading Node version, may need to revise tsconfig to reference new major version base tsconfig.json

Previous upgrade issues: #216
